name = "miniopenfx"
main = "src/index.ts"
compatibility_date = "2026-01-07"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{ name = "FX_DO", class_name = "FxPricesDO" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FxPricesDO"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "pricecache"
id = "b4f68db09abb4d81a08997336695765b"